name: "Setup Kyma CLI"
description: "The action setups Kyma CLI (Usable with SAP BTP, Kyma environment)."
inputs:
  version:
    description: "Version of Kyma CLI to use (e.g '3.1.0', 'latest', 'stable', 'nightly')"
    required: false
    default: "latest"
  target-dir:
    description: "Directory to install Kyma CLI to"
    required: false
    default: ""
  token:
    description: "Token to access GitHub API"
    required: false
    default: ""
  force:
    description: "Skip cache and force reinstallation"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: "Choose token header"
      id: choose_token
      shell: bash
      run: |
        if [[ -n "${{ inputs.token }}" ]]; then
          echo "Challanging provided token"
          curl_output="$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/)"
          
          if [[ "$(echo "$curl_output" | jq -r '.message')" == "Bad credentials" ]]; then
            echo "Provided token is invalid"
          else
            echo "Provided token is valid"
            echo "flag=-H \"Authorization: Bearer ${{ inputs.token }}\" >> $GITHUB_ENV"
            exit 0
          fi
        fi

        if [[ -n "${{ github.token }}" ]]; then
          echo "Challanging GITHUB_TOKEN"
          curl_output="$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/)"
          
          if [[ "$(echo "$curl_output" | jq -r '.message')" == "Bad credentials" ]]; then
            echo "GITHUB_TOKEN is invalid"
          else
            echo "GITHUB_TOKEN is valid"
            echo "flag=-H \"Authorization: Bearer ${{ github.token }}\" >> $GITHUB_ENV"
            exit 0
          fi
        fi

        echo "No valid token provided, proceeding without authentication. Note that this may cause issues with API rate limits."

    - name: "Calculate cache key"
      id: calculate
      shell: bash
      run: |
        KYMA_CLI_VERSION="${{ inputs.version }}"

        if [[ -z "${KYMA_CLI_VERSION}" || "${KYMA_CLI_VERSION}" == "latest" ]]; then
          KYMA_CLI_VERSION="$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ steps.choose_token.outputs.flag }} \
            https://api.github.com/repos/kyma-project/cli/releases | jq -r '[.[] | select(.name != "0.0.0-dev")][0].name')"
        elif [[ "${KYMA_CLI_VERSION}" == "stable" ]]; then
          KYMA_CLI_VERSION="$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${{ steps.choose_token.outputs.flag }} \
            https://api.github.com/repos/kyma-project/cli/releases/latest | jq -r '.name')"
        elif [[ "${KYMA_CLI_VERSION}" == "nightly" ]]; then
          KYMA_CLI_VERSION="0.0.0-dev"
        fi
        echo "kyma_cli_version=${KYMA_CLI_VERSION}" >> $GITHUB_OUTPUT

        ARCH="$(uname -m)"
        if [ "${ARCH}" = "amd64" ]; then
            ARCH="x86_64"
        elif [ "${ARCH}" = "aarch64" ]; then
            ARCH="arm64"
        fi
        echo "kyma_cli_arch=${ARCH}" >> $GITHUB_OUTPUT

        OS="$(uname -s)"
        if [[ "${OS}" =~ MINGW* ]]; then
          OS="Windows"
        fi

        if [[ "${OS}" == "Windows" ]]; then
          target=/c/vcpkg
          if [[ -n "${TARGET_DIR}" ]]; then
            target="${TARGET_DIR}"
          fi
          echo "kyma_cli_path=${target}/kyma.exe" >> $GITHUB_OUTPUT
        else 
          target=~/.local/bin
          if [[ -n "${TARGET_DIR}" ]]; then
            target="${TARGET_DIR}"
          fi
          echo "kyma_cli_path=${target}/kyma" >> $GITHUB_OUTPUT
        fi
      env:
        TARGET_DIR: ${{ inputs.target-dir }}
    - name: Kyma CLI cache"
      id: cache
      uses: actions/cache@v5
      with:
        path: |
          ${{ steps.calculate.outputs.kyma_cli_path }}
        key: kyma-cli-${{ runner.os }}-${{ steps.calculate.outputs.kyma_cli_arch }}-${{ steps.calculate.outputs.kyma_cli_version }}

    - name: "Install Kyma CLI"
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.force == 'true' || steps.calculate.outputs.kyma_cli_version == '0.0.0-dev'
      shell: bash
      run: |
        set -e

        KYMA_CLI_VERSION="${{ steps.calculate.outputs.kyma_cli_version }}"

        OS="$(uname -s)"
        # if OS contains MINGW prefix then change OS to Windows
        if [[ "${OS}" =~ MINGW* ]]; then
          OS="Windows"
        fi

        EXT="tar.gz"
        if [[ "${OS}" == "Windows" ]]; then
          EXT="zip"
        fi
        filename="kyma_${OS}_${ARCH}.${EXT}"
        echo "Downloading ${filename}"

        CLI_TMPDIR=cli-$(date "+%Y-%m-%d_%H_%M_%S")
        mkdir -p "${CLI_TMPDIR}"
        curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ steps.choose_token.outputs.flag }} \
          "https://github.com/kyma-project/cli/releases/download/${KYMA_CLI_VERSION}/${filename}" > "${CLI_TMPDIR}/cli.${EXT}"

        if [[ "${OS}" == "Windows" ]]; then
          unzip "${CLI_TMPDIR}/cli.zip" -d "${CLI_TMPDIR}"
          mkdir -p "${TARGET_PATH%/kyma.exe}"
          mv "${CLI_TMPDIR}/kyma.exe" "${TARGET_PATH}"
          rm -r "${CLI_TMPDIR}"
          echo "Installed $(${TARGET_PATH} version) to $(readlink -f "${TARGET_PATH}")"
          exit 0
        fi

        force_local=""
        if [[ "$OS" == "Linux" ]]; then
          force_local="--force-local"
        fi

        tar "${force_local}" -zxvf "${CLI_TMPDIR}/cli.tar.gz" kyma 
        mkdir -p "${TARGET_PATH%/kyma}"
        mv kyma "${TARGET_PATH}"
        rm -r "${CLI_TMPDIR}"
        echo "Installed $(${TARGET_PATH} version) to $(readlink -f "${TARGET_PATH}")"
      env:
        KYMA_CLI_VERSION: ${{ steps.calculate.outputs.kyma_cli_version }}
        TARGET_PATH: ${{ steps.calculate.outputs.kyma_cli_path }}
        ARCH: ${{ steps.calculate.outputs.kyma_cli_arch }}
    - name: "adjust PATH"
      if: always()
      shell: bash
      run: |
        OS="$(uname -s)"
        # if OS contains MINGW prefix then change OS to Windows
        if [[ "${OS}" =~ MINGW* ]]; then
          OS="Windows"
        fi

        if [[ "${OS}" == "Windows" ]]; then
          echo "${TARGET_PATH%/kyma.exe}" >> $GITHUB_PATH
        else
          echo "${TARGET_PATH%/kyma}" >> $GITHUB_PATH
        fi
      env:
        TARGET_PATH: ${{ steps.calculate.outputs.kyma_cli_path }}
branding:
  icon: "download"
  color: "blue"
