name: "Kubeconfig generate"
description: "Generate kubeconfig with an OIDC authentication"
inputs:
  #cluster authentication via an OIDC connection
  api-server-url:
    description: "Kubernetes API server URL of the Kyma cluster"
    required: true
  ca-crt:
    description: "base64-encoded CA certificate for the API server"
    required: true
  audience:
    description: "OIDC audience"
    required: false
    default: ""
outputs:
  kubeconfig:
    description: "generated kubeconfig"
    value: "${{ steps.oidc.outputs.kubeconfig }}"
  kubeconfig-base64:
    description: "base64 encoded generated kubeconfig"
    value: "${{ steps.oidc.outputs.kubeconfig_base }}"
runs:
  using: composite
  steps:
    - name: "get OIDC kubeconfig"
      id: oidc
      if: ${{ inputs.kubeconfig == '' }}
      shell: bash
      run: |
        generate_flags=()
        generate_flags+=("--audience" "${AUDIENCE}")
        generate_flags+=("--server" "${API_SERVER_URL}")
        generate_flags+=("--certificate-authority-data" "${CA_CRT}")
        kubeconfig_path="action_kubeconfig.yaml"
        generate_flags+=("--output" "${kubeconfig_path}")
        kyma alpha kubeconfig generate "${generate_flags[@]}"

        echo 'kubeconfig<<EOF'  >> $GITHUB_OUTPUT
        cat "${kubeconfig_path}" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

        kubeconfig64="$(cat "${kubeconfig_path}" | base64 -w 0)"
        echo "kubeconfig_base=${kubeconfig64}" >> $GITHUB_OUTPUT
      env:
        AUDIENCE: "${{ inputs.audience }}"
        API_SERVER_URL: "${{ inputs.api-server-url }}"
        CA_CRT: "${{ inputs.ca-crt }}"
